import { TOKEN } from './constants';

export const NFTS: { [key: string]: Nft } = {
  '0月' : {
    month: 0,
    level: 0,
    imageUrl: '/images/random-box.jpg',
    name : '黑胡 RANDOMBOX',
    price: {
      [TOKEN.PSUB]: 400,
      [TOKEN.T_PSUB]: 400,
      [TOKEN.USDT]: 21.35,
      [TOKEN.BNB]: 0.0413,
    },
  },
  '1月': {
    month: 1,
    level: 1,
    imageUrl: '/images/1.webp',
    name : '松鹤',
    price: {
      [TOKEN.PSUB]: 100,
      [TOKEN.T_PSUB]: 100,
      [TOKEN.USDT]: 3.05,
      [TOKEN.BNB]: 0.0059,
    },
  },
  '2月': {
    month: 2,
    level: 2,
    imageUrl: '/images/2.webp',
    name : '梅鸟',
    price: {
      [TOKEN.PSUB]: 200,
      [TOKEN.T_PSUB]: 200,
      [TOKEN.USDT]: 6.1,
      [TOKEN.BNB]: 0.0118,
    },
  },
  '3月': {
    month: 3,
    level: 3,
    imageUrl: '/images/3.webp',
    name : '樱花',
    price: {
      [TOKEN.PSUB]: 400,
      [TOKEN.T_PSUB]: 400,
      [TOKEN.USDT]: 12.2,
      [TOKEN.BNB]: 0.0236,
    },
  },
  '4月': {
    month: 4,
    level: 4,
    imageUrl: '/images/4.webp',
    name : '黑胡',
    price: {
      [TOKEN.PSUB]: 800,
      [TOKEN.T_PSUB]: 800,
      [TOKEN.USDT]: 544,
      [TOKEN.BNB]: 0.0472,
    },
  },
  '5月': {
    month: 5,
    level: 5,
    imageUrl: '/images/5.webp',
    name : '兰草',
    price: {
      [TOKEN.PSUB]: 1_600,
      [TOKEN.T_PSUB]: 1_600,
      [TOKEN.USDT]: 1_088,
      [TOKEN.BNB]: 0.0944,
    },
  },
  '6月': {
    month: 6,
    level: 6,
    imageUrl: '/images/6.webp',
    name : '牡丹',
    price: {
      [TOKEN.PSUB]: 3_200,
      [TOKEN.T_PSUB]: 3_200,
      [TOKEN.USDT]: 2_176,
      [TOKEN.BNB]: 0.1888,
    },
  },
  '7月': {
    month: 7,
    level: 7,
    imageUrl: '/images/7.webp',
    name : '红胡',
    price: {
      [TOKEN.PSUB]: 6_400,
      [TOKEN.T_PSUB]: 6_400,
      [TOKEN.USDT]: 4_352,
      [TOKEN.BNB]: 0.3776,
    },
  },
  '8月': {
    month: 8,
    level: 8,
    imageUrl: '/images/8.webp',
    name : '空山',
    price: {
      [TOKEN.PSUB]: 12_800,
      [TOKEN.T_PSUB]: 12_800,
      [TOKEN.USDT]: 8_704,
      [TOKEN.BNB]: 0.7552,
    },
  },
  '9月': {
    month: 9,
    level: 9,
    imageUrl: '/images/9.webp',
    name : '菊俊',
    price: {
      [TOKEN.PSUB]: 25_600,
      [TOKEN.T_PSUB]: 25_600,
      [TOKEN.USDT]: 17_408,
      [TOKEN.BNB]: 1.5105,
    },
  },
  '10月': {
    month: 10,
    level: 10,
    imageUrl: '/images/10.webp',
    name : '丹枫',
    price: {
      [TOKEN.PSUB]: 51_200,
      [TOKEN.T_PSUB]: 51_200,
      [TOKEN.USDT]: 34_816,
      [TOKEN.BNB]: 3.0208,
    },
  },
  '11月': {
    month: 11,
    level: 11,
    imageUrl: '/images/11.webp',
    name : '梧桐',
    price: {
      [TOKEN.PSUB]: 102_400,
      [TOKEN.T_PSUB]: 102_400,
      [TOKEN.USDT]: 69_632,
      [TOKEN.BNB]: 6.0416,
    },
  },
  '12月': {
    month: 12,
    level: 12,
    imageUrl: '/images/12.webp',
    name : '雨',
    price: {
      [TOKEN.PSUB]: 204_800,
      [TOKEN.T_PSUB]: 204_800,
      [TOKEN.USDT]: 139_264,
      [TOKEN.BNB]: 12.0832,
    },
  },
};
